[project]
name = "logsmith"
version = "10.1.0-rc.2"
requires-python = "==3.13.7"
dependencies = [
    "boto3==1.35.31",
    "pyinstaller==6.10.0",
    "pyqt6==6.7.1",
    "pytest==8.0.2",
    "pytest-mock==3.15.1",
    "ruamel-yaml==0.18.6",
]

[tool.pytest.ini_options]
addopts = "-vv"
